name: .NET

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: ./publish

  web-deploy:
    needs: build
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: publish

      - name: Delete all file on ftp server
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: site27007.siteasp.net
          user: site27007
          password: W#o9mF2=3%Jc
          remoteFiles: "*.*"
          remoteDirectories: "*"
          workingDir: /wwwroot
          ignoreSSL: "1"

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: site27007.siteasp.net
          username: site27007
          password: W#o9mF2=3%Jc
          local-dir: ./
          server-dir: ./wwwroot/
          dangerous-clean-slate: true
          log-level: verbose
